#spring.application.name=Accounts

#Server Listening Port
server:
  port: 8080

spring:
  application:
    name: "accounts"
    version: v1
  #    Database Connection Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eazybank_microservices}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active:
      - "default"

# Enabling all the endpoints of Spring boot actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"


