#spring.application.name=Accounts

#Server Listening Port
server:
  port: 8080

spring:
  application:
    name: Accounts
    version: v1
#    Database Connection Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eazybank_microservices}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

