#spring.application.name=Accounts

#Server Listening Port
server:
  port: 8080

spring:
  application:
    name: Accounts
    version: v1
#    Database Connection Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eazybank_microservices}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import:
      - "application_qa.yml"
      -  "application_prod.yml"
  profiles:
    active:
      - "qa"
# Setting build version
build:
  version: "3.1"

accounts:
  message: "Welcome to Accounts Services related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

