#spring.application.name=Accounts

#Server Listening Port
server:
  port: 8080

spring:
  application:
    name: Accounts
    version: v1
#    Database Connection Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME:eazybank_microservices}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

